### Objetivo

El análisis se realiza sobre los datos almacenados en PostgreSQL, la base de datos que utiliza nuestro proyecto COMPLEX SOLUTIONS S.L.

Utilizaremos Python y Pandas para explorar los datos, preparar las tablas necesarias y calcular indicadores de negocio. Para conectar ambos entornos emplearemos SQLAlchemy junto con el controlador psycopg.

Las credenciales se obtienen del archivo .env, evitando escribir directamente la contraseña en el notebook.

Antes de comenzar, comprobaremos que la conexión se ha establecido correctamente y que estamos accediendo a la base de datos y al usuario esperados.

### 1. Conexión a PostgreSQL y configuración

In [133]:
import os
import pandas as pd
import psycopg
import sqlalchemy

from sqlalchemy import create_engine

from dotenv import load_dotenv

load_dotenv()

DB_NAME = os.getenv("POSTGRES_DB")
DB_USER = os.getenv("POSTGRES_USER")
DB_PASSWORD = os.getenv("POSTGRES_PASSWORD")
DB_HOST = "localhost"
DB_PORT = os.getenv("POSTGRES_PORT")

### 2. Conexión:

In [134]:
engine = create_engine(
    f"postgresql+psycopg://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

with engine.connect() as connection:
    result = connection.exec_driver_sql(
        "SELECT current_database(), current_user;"
    ).fetchone()

print("Conexión establecida correctamente.")
print("Base de datos:", result[0])
print("Usuario:", result[1])

Conexión establecida correctamente.
Base de datos: complex_solutions
Usuario: complex_admin

### Exploración de los clientes

El primer paso consiste en conocer la estructura de la cartera de clientes de COMPLEX SOLUTIONS S.L.

Antes de realizar cálculos o extraer conclusiones, comprobaremos las dimensiones del conjunto de datos, los campos disponibles, los tipos de datos y la presencia de valores ausentes.

Esta exploración inicial nos ayudará a comprender la información con la que trabajamos y a detectar posibles problemas de calidad que debamos investigar posteriormente.

### 3. Exploración de clientes

In [135]:
query = """
SELECT *
FROM customers;
"""

customers_df = pd.read_sql(query, engine)

customers_df.head()

,customer_id,customer_type,company_name,customer_segment,city,province,signup_date,acquisition_channel,sales_rep_id
0,1,B2B,Customer 00001,SMB,Madrid,Madrid,2026-09-08,OUTBOUND_SALES,1.0
1,2,B2C,Customer 00002,CONSUMER,Barcelona,Barcelona,2020-09-17,ONLINE,NaN
2,3,B2C,Customer 00003,CONSUMER,Valencia,Valencia,2024-04-25,ONLINE,NaN
3,4,B2B,Customer 00004,SMB,Sevilla,Sevilla,2024-04-12,OUTBOUND_SALES,1.0
4,5,B2C,Customer 00005,CONSUMER,Bilbao,Bizkaia,2026-09-06,ONLINE,NaN

### 4. Dimensiones:

In [136]:
customers_df.shape

(362, 9)

### 5. Columnas:

In [137]:
customers_df.columns

Index(['customer_id', 'customer_type', 'company_name', 'customer_segment',
       'city', 'province', 'signup_date', 'acquisition_channel',
       'sales_rep_id'],
      dtype='str')

### 6. Información general:

In [138]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          362 non-null    int64
 1   customer_type        362 non-null    str
 2   company_name         362 non-null    str
 3   customer_segment     362 non-null    str
 4   city                 362 non-null    str
 5   province             362 non-null    str
 6   signup_date          362 non-null    object
 7   acquisition_channel  362 non-null    str
 8   sales_rep_id         122 non-null    float64
dtypes: float64(1), int64(1), object(1), str(6)
memory usage: 25.6+ KB

### 7. Valores ausentes:

In [139]:
customers_df.isna().sum()

customer_id              0
customer_type            0
company_name             0
customer_segment         0
city                     0
province                 0
signup_date              0
acquisition_channel      0
sales_rep_id           240
dtype: int64

In [140]:
customers_df[customers_df["sales_rep_id"].isna()]["customer_type"].value_counts()

customer_type
B2C    240
Name: count, dtype: int64

In [141]:
customers_df[
    (customers_df["customer_type"] == "B2B") &
    (customers_df["sales_rep_id"].isna())
]

Empty DataFrame
Columns: [customer_id, customer_type, company_name, customer_segment, city, province, signup_date, acquisition_channel, sales_rep_id]
Index: []

In [142]:
customers_df[
    customers_df["customer_type"] == "B2C"
]["sales_rep_id"].notna().sum()

np.int64(0)

In [143]:
customers_df["customer_type"].value_counts()

customer_type
B2C    240
B2B    122
Name: count, dtype: int64

In [144]:
customers_df["customer_type"].value_counts(normalize=True)

customer_type
B2C    0.662983
B2B    0.337017
Name: proportion, dtype: float64

In [145]:
customers_df["acquisition_channel"].value_counts()

acquisition_channel
ONLINE            241
OUTBOUND_SALES    121
Name: count, dtype: int64

In [146]:
pd.crosstab(
    customers_df["customer_type"],
    customers_df["acquisition_channel"]
)

acquisition_channel  ONLINE  OUTBOUND_SALES
customer_type
B2B                       1             121
B2C                     240               0

### Exploración y preparación de las ventas

Una vez examinada la estructura de la cartera de clientes, pasamos a analizar la actividad comercial de COMPLEX SOLUTIONS S.L.

Cargaremos los registros de ventas y sus líneas de detalle para conocer su estructura, comprobar los datos disponibles y calcular los principales indicadores económicos: facturación, costes, beneficio bruto y margen bruto.

Posteriormente, prepararemos los datos para estudiar la evolución de las ventas y la rentabilidad a lo largo del tiempo.

In [147]:
query_sales = """
SELECT *
FROM sales;
"""

sales_df = pd.read_sql(query_sales, engine)

sales_df.head()

   sale_id  customer_id  employee_id   sale_date         channel     status
0        1          177            1  2026-11-06  PHYSICAL_STORE  CONFIRMED
1        2          317            1  2024-06-12          ONLINE  CONFIRMED
2        3           55            1  2026-06-30             B2B  CONFIRMED
3        4          345            1  2025-06-10          ONLINE  CONFIRMED
4        5          166            1  2025-08-22             B2B  CONFIRMED

In [148]:
sales_df.shape

(2101, 6)

In [149]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2101 entries, 0 to 2100
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sale_id      2101 non-null   int64
 1   customer_id  2101 non-null   int64
 2   employee_id  2101 non-null   int64
 3   sale_date    2101 non-null   object
 4   channel      2101 non-null   str
 5   status       2101 non-null   str
dtypes: int64(3), object(1), str(2)
memory usage: 98.6+ KB

### Carga de las líneas de venta

In [150]:
query_sale_items = """
SELECT *
FROM sale_items;
"""

sale_items_df = pd.read_sql(query_sale_items, engine)

sale_items_df.head()

,sale_item_id,sale_id,product_id,quantity,unit_price,discount,unit_cost
0,1,1,8,2,458.70,0.0534,462.04
1,2,2,3,2,68.97,0.0518,61.10
2,3,3,12,2,1310.76,0.2107,1100.24
3,4,4,118,2,309.38,0.0386,245.25
4,5,5,28,3,1419.99,0.2015,1082.37

In [151]:
sale_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2101 entries, 0 to 2100
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sale_item_id  2101 non-null   int64
 1   sale_id       2101 non-null   int64
 2   product_id    2101 non-null   int64
 3   quantity      2101 non-null   int64
 4   unit_price    2101 non-null   float64
 5   discount      2101 non-null   float64
 6   unit_cost     2101 non-null   float64
dtypes: float64(3), int64(4)
memory usage: 115.0 KB

In [152]:
sale_items_df["revenue"] = (
    sale_items_df["quantity"]
    * sale_items_df["unit_price"]
    * (1 - sale_items_df["discount"])
)

sale_items_df["total_cost"] = (
    sale_items_df["quantity"]
    * sale_items_df["unit_cost"]
)

sale_items_df["gross_profit"] = (
    sale_items_df["revenue"]
    - sale_items_df["total_cost"]
)

In [153]:
sale_items_df[
    [
        "quantity",
        "unit_price",
        "discount",
        "unit_cost",
        "revenue",
        "total_cost",
        "gross_profit",
    ]
].head()

,quantity,unit_price,discount,unit_cost,revenue,total_cost,gross_profit
0,2,458.70,0.0534,462.04,868.410840,924.08,-55.669160
1,2,68.97,0.0518,61.10,130.794708,122.20,8.594708
2,2,1310.76,0.2107,1100.24,2069.165736,2200.48,-131.314264
3,2,309.38,0.0386,245.25,594.875864,490.50,104.375864
4,3,1419.99,0.2015,1082.37,3401.586045,3247.11,154.476045

In [154]:
total_revenue = sale_items_df["revenue"].sum()
total_cost = sale_items_df["total_cost"].sum()
total_gross_profit = sale_items_df["gross_profit"].sum()

gross_margin = total_gross_profit / total_revenue * 100

print("Facturación total:", round(total_revenue, 2), "€")
print("Coste total:", round(total_cost, 2), "€")
print("Beneficio bruto:", round(total_gross_profit, 2), "€")
print("Margen bruto:", round(gross_margin, 2), "%")

Facturación total: 2269624.61 €
Coste total: 2112374.6 €
Beneficio bruto: 157250.01 €
Margen bruto: 6.93 %

### Estados de las ventas

In [155]:
sales_df["status"].value_counts()

status
CONFIRMED    2101
Name: count, dtype: int64

### Unión de las ventas con sus líneas de detalle

In [156]:
sales_analysis_df = sales_df.merge(
    sale_items_df,
    on="sale_id",
    how="inner"
)

sales_analysis_df.head()

,sale_id,customer_id,employee_id,sale_date,channel,status,sale_item_id,product_id,quantity,unit_price,discount,unit_cost,revenue,total_cost,gross_profit
0,1,177,1,2026-11-06,PHYSICAL_STORE,CONFIRMED,1,8,2,458.70,0.0534,462.04,868.410840,924.08,-55.669160
1,2,317,1,2024-06-12,ONLINE,CONFIRMED,2,3,2,68.97,0.0518,61.10,130.794708,122.20,8.594708
2,3,55,1,2026-06-30,B2B,CONFIRMED,3,12,2,1310.76,0.2107,1100.24,2069.165736,2200.48,-131.314264
3,4,345,1,2025-06-10,ONLINE,CONFIRMED,4,118,2,309.38,0.0386,245.25,594.875864,490.50,104.375864
4,5,166,1,2025-08-22,B2B,CONFIRMED,5,28,3,1419.99,0.2015,1082.37,3401.586045,3247.11,154.476045

In [157]:
sales_analysis_df.shape

(2101, 15)

### Preparación de las fechas

In [159]:
sales_analysis_df["sale_date"] = pd.to_datetime(
    sales_analysis_df["sale_date"]
)

In [160]:
sales_analysis_df["sale_date"].dtype

dtype('<M8[s]')

### Extracción y comprobación del año

In [161]:
sales_analysis_df["year"] = sales_analysis_df["sale_date"].dt.year

sales_analysis_df[["sale_date", "year"]].head()

   sale_date  year
0 2026-11-06  2026
1 2024-06-12  2024
2 2026-06-30  2026
3 2025-06-10  2025
4 2025-08-22  2025

###  Evolución anual de la rentabilidad

Una vez calculados los principales indicadores económicos, analizamos su evolución a lo largo del tiempo.

El objetivo es comprobar si el crecimiento de la facturación se traduce también en una mejora del beneficio bruto y del margen comercial.

Para profundizar en los resultados, examinaremos la evolución de los descuentos y de los precios y costes unitarios. Estas variables pueden ayudarnos a identificar posibles factores relacionados con los cambios en la rentabilidad.

Los resultados servirán como punto de partida para los análisis posteriores por categoría y producto.

In [162]:
yearly_analysis = sales_analysis_df.groupby("year").agg(
    revenue=("revenue", "sum"),
    total_cost=("total_cost", "sum"),
    gross_profit=("gross_profit", "sum")
)

yearly_analysis["gross_margin"] = (
    yearly_analysis["gross_profit"] / yearly_analysis["revenue"] * 100
)

yearly_analysis.round(2)

        revenue  total_cost  gross_profit  gross_margin
year
2020   77354.01    69404.00       7950.01         10.28
2021  132597.28   116484.69      16112.59         12.15
2022  257563.13   236108.68      21454.45          8.33
2023  356641.88   324928.24      31713.64          8.89
2024  394663.38   362183.94      32479.44          8.23
2025  510725.00   480281.25      30443.75          5.96
2026  540079.92   522983.80      17096.12          3.17

In [163]:
yearly_discounts = sales_analysis_df.groupby("year").agg(
    average_discount=("discount", "mean"),
    total_revenue=("revenue", "sum")
)

yearly_discounts["average_discount"] = (
    yearly_discounts["average_discount"] * 100
)

yearly_discounts.round(2)

      average_discount  total_revenue
year
2020              9.53       77354.01
2021              8.41      132597.28
2022              9.22      257563.13
2023              8.63      356641.88
2024              8.63      394663.38
2025              8.74      510725.00
2026              9.13      540079.92

In [164]:
yearly_costs = sales_analysis_df.groupby("year").agg(
    average_unit_cost=("unit_cost", "mean"),
    average_unit_price=("unit_price", "mean")
)

yearly_costs.round(2)

      average_unit_cost  average_unit_price
year
2020             372.61              459.40
2021             425.55              525.04
2022             449.17              540.60
2023             538.30              645.82
2024             501.13              597.13
2025             556.55              648.61
2026             532.30              606.35

### Análisis de rentabilidad por categoría

La evolución global del margen nos indica si la rentabilidad de la empresa está mejorando o empeorando, pero no nos permite identificar qué productos o categorías contribuyen a ese resultado.

Para profundizar en el análisis, incorporamos la información de productos y categorías a las líneas de venta.

A continuación, calculamos la facturación, los costes, el beneficio bruto, las unidades vendidas y el margen de cada categoría. Esto nos permitirá comparar su contribución económica y detectar diferencias relevantes de rentabilidad.

### Incorporación de productos y categorías

In [165]:
query_products = """
SELECT
    product_id,
    product_name,
    category_id
FROM products;
"""

products_df = pd.read_sql(query_products, engine)

products_df.head()

   product_id             product_name  category_id
0           1   Acer Computers Model 1            1
1           2  ASUS Components Model 2            2
2           3    Dell Monitors Model 3            3
3           4   HP Peripherals Model 4            4
4           5   Lenovo Storage Model 5            5

### Consulta de categorías

In [166]:
query_categories = """
SELECT
    category_id,
    category_name
FROM categories;
"""

categories_df = pd.read_sql(query_categories, engine)

categories_df

   category_id category_name
0            1     Computers
1            2    Components
2            3      Monitors
3            4   Peripherals
4            5       Storage
5            6    Networking
6            7   Accessories
7            8      Printing
8            9       Servers
9           10      Security

### Unión con productos y categorías

In [167]:
sales_categories_df = sales_analysis_df.merge(
    products_df,
    on="product_id",
    how="left"
)

sales_categories_df = sales_categories_df.merge(
    categories_df,
    on="category_id",
    how="left"
)

sales_categories_df.head()

,sale_id,customer_id,employee_id,sale_date,channel,status,sale_item_id,product_id,quantity,unit_price,discount,unit_cost,revenue,total_cost,gross_profit,year,product_name,category_id,category_name
0,1,177,1,2026-11-06,PHYSICAL_STORE,CONFIRMED,1,8,2,458.70,0.0534,462.04,868.410840,924.08,-55.669160,2026,Samsung Printing Model 8,8,Printing
1,2,317,1,2024-06-12,ONLINE,CONFIRMED,2,3,2,68.97,0.0518,61.10,130.794708,122.20,8.594708,2024,Dell Monitors Model 3,3,Monitors
2,3,55,1,2026-06-30,B2B,CONFIRMED,3,12,2,1310.76,0.2107,1100.24,2069.165736,2200.48,-131.314264,2026,ASUS Components Model 12,2,Components
3,4,345,1,2025-06-10,ONLINE,CONFIRMED,4,118,2,309.38,0.0386,245.25,594.875864,490.50,104.375864,2025,Samsung Printing Model 118,8,Printing
4,5,166,1,2025-08-22,B2B,CONFIRMED,5,28,3,1419.99,0.2015,1082.37,3401.586045,3247.11,154.476045,2025,Samsung Printing Model 28,8,Printing

### Comprobación de la unión

In [168]:
sales_categories_df[
    ["product_name", "category_name", "quantity", "revenue", "gross_profit"]
].head(10)

,product_name,category_name,quantity,revenue,gross_profit
0,Samsung Printing Model 8,Printing,2,868.410840,-55.669160
1,Dell Monitors Model 3,Monitors,2,130.794708,8.594708
2,ASUS Components Model 12,Components,2,2069.165736,-131.314264
3,Samsung Printing Model 118,Printing,2,594.875864,104.375864
4,Samsung Printing Model 28,Printing,3,3401.586045,154.476045
5,Acer Computers Model 11,Computers,3,2992.789074,473.239074
6,Lenovo Storage Model 65,Storage,2,55.732624,2.132624
7,Samsung Printing Model 38,Printing,3,779.506200,68.056200
8,Samsung Printing Model 88,Printing,1,486.513250,46.993250
9,Dell Monitors Model 23,Monitors,2,613.120960,-57.959040

### Análisis de rentabilidad por categoría

In [169]:
category_analysis = sales_categories_df.groupby("category_name").agg(
    total_revenue=("revenue", "sum"),
    total_cost=("total_cost", "sum"),
    gross_profit=("gross_profit", "sum"),
    units_sold=("quantity", "sum")
)

category_analysis["gross_margin"] = (
    category_analysis["gross_profit"]
    / category_analysis["total_revenue"]
    * 100
)

category_analysis = category_analysis.sort_values(
    "total_revenue",
    ascending=False
)

category_analysis.round(2)

,total_revenue,total_cost,gross_profit,units_sold,gross_margin
category_name,,,,,
Networking,302435.31,283178.26,19257.05,398,6.37
Peripherals,294818.75,273242.02,21576.73,461,7.32
Monitors,273579.86,246576.03,27003.83,491,9.87
Computers,239905.18,222438.83,17466.35,695,7.28
Security,229112.21,216927.58,12184.63,329,5.32
Components,223006.20,201014.24,21991.96,539,9.86
Storage,215983.59,217028.93,-1045.34,355,-0.48
Printing,199918.36,183138.71,16779.65,319,8.39
Accessories,150421.91,130228.26,20193.65,335,13.42
Servers,140443.24,138601.74,1841.50,290,1.31

### Análisis de la categoría Storage

In [170]:
storage_analysis = (
    sales_categories_df[
        sales_categories_df["category_name"] == "Storage"
    ]
    .groupby("product_name")
    .agg(
        revenue=("revenue", "sum"),
        total_cost=("total_cost", "sum"),
        gross_profit=("gross_profit", "sum"),
        units_sold=("quantity", "sum")
    )
)

storage_analysis["gross_margin"] = (
    storage_analysis["gross_profit"]
    / storage_analysis["revenue"]
    * 100
)

storage_analysis = storage_analysis.sort_values(
    "gross_profit",
    ascending=True
)

storage_analysis.round(2)

,revenue,total_cost,gross_profit,units_sold,gross_margin
product_name,,,,,
Lenovo Storage Model 15,111588.92,119137.28,-7548.36,70,-6.76
Lenovo Storage Model 85,2117.26,2304.49,-187.23,14,-8.84
Lenovo Storage Model 65,548.20,563.25,-15.05,21,-2.74
Lenovo Storage Model 115,1816.56,1742.27,74.29,29,4.09
Lenovo Storage Model 45,33257.50,33059.60,197.90,26,0.60
Lenovo Storage Model 55,2304.04,2080.80,223.24,6,9.69
Lenovo Storage Model 105,3800.16,3570.00,230.16,6,6.06
Lenovo Storage Model 25,6810.69,6515.99,294.70,11,4.33
Lenovo Storage Model 35,2544.56,2107.32,437.24,34,17.18
Lenovo Storage Model 95,11524.44,10590.24,934.20,6,8.11
Lenovo Storage Model 5,20551.67,18464.99,2086.68,113,10.15
Lenovo Storage Model 75,19119.57,16892.70,2226.87,19,11.65

In [171]:
storage_analysis["revenue_share"] = (
    storage_analysis["revenue"]
    / storage_analysis["revenue"].sum()
    * 100
)

storage_analysis["profit_share"] = (
    storage_analysis["gross_profit"]
    / storage_analysis["gross_profit"].sum()
    * 100
)

storage_analysis.round(2)

,revenue,total_cost,gross_profit,units_sold,gross_margin,revenue_share,profit_share
product_name,,,,,,,
Lenovo Storage Model 15,111588.92,119137.28,-7548.36,70,-6.76,51.67,722.09
Lenovo Storage Model 85,2117.26,2304.49,-187.23,14,-8.84,0.98,17.91
Lenovo Storage Model 65,548.20,563.25,-15.05,21,-2.74,0.25,1.44
Lenovo Storage Model 115,1816.56,1742.27,74.29,29,4.09,0.84,-7.11
Lenovo Storage Model 45,33257.50,33059.60,197.90,26,0.60,15.40,-18.93
Lenovo Storage Model 55,2304.04,2080.80,223.24,6,9.69,1.07,-21.36
Lenovo Storage Model 105,3800.16,3570.00,230.16,6,6.06,1.76,-22.02
Lenovo Storage Model 25,6810.69,6515.99,294.70,11,4.33,3.15,-28.19
Lenovo Storage Model 35,2544.56,2107.32,437.24,34,17.18,1.18,-41.83
Lenovo Storage Model 95,11524.44,10590.24,934.20,6,8.11,5.34,-89.37
Lenovo Storage Model 5,20551.67,18464.99,2086.68,113,10.15,9.52,-199.62
Lenovo Storage Model 75,19119.57,16892.70,2226.87,19,11.65,8.85,-213.03

### Productos con pérdidas

In [172]:
storage_analysis[
    storage_analysis["gross_profit"] < 0
][
    ["revenue", "total_cost", "gross_profit", "units_sold", "gross_margin"]
].round(2)

,revenue,total_cost,gross_profit,units_sold,gross_margin
product_name,,,,,
Lenovo Storage Model 15,111588.92,119137.28,-7548.36,70,-6.76
Lenovo Storage Model 85,2117.26,2304.49,-187.23,14,-8.84
Lenovo Storage Model 65,548.20,563.25,-15.05,21,-2.74

### Investigación de la rentabilidad del Lenovo Storage Model 15

El análisis por producto ha identificado referencias con beneficio bruto negativo. Para investigar uno de los casos más relevantes, examinamos las ventas confirmadas del Lenovo Storage Model 15.

Estudiaremos su evolución anual, incluyendo las unidades vendidas, los precios, los descuentos, los costes y el beneficio bruto.

El objetivo es buscar indicios que ayuden a explicar las pérdidas del producto y distinguir entre un problema persistente y un deterioro que se produce a lo largo del tiempo.

Este análisis constituye una investigación específica de un producto, pero sus conclusiones no deben extrapolarse automáticamente al conjunto de la empresa.

In [173]:
query_storage = """
SELECT
    s.sale_id,
    s.sale_date,
    s.channel,
    si.quantity,
    si.unit_price,
    si.discount,
    si.unit_cost,
    si.quantity * si.unit_price * (1 - si.discount) AS revenue,
    si.quantity * si.unit_cost AS total_cost,
    si.quantity * (
        si.unit_price * (1 - si.discount) - si.unit_cost
    ) AS gross_profit
FROM sales s
JOIN sale_items si
    ON s.sale_id = si.sale_id
JOIN products p
    ON si.product_id = p.product_id
WHERE p.product_name = 'Lenovo Storage Model 15'
    AND s.status = 'CONFIRMED'
ORDER BY s.sale_date;
"""

storage_sales_df = pd.read_sql(query_storage, engine)

storage_sales_df.head(10)

,sale_id,sale_date,channel,quantity,unit_price,discount,unit_cost,revenue,total_cost,gross_profit
0,783,2020-05-16,ONLINE,3,1752.3,0.0776,1593.00,4848.96456,4779.00,69.96456
1,648,2020-06-28,PHYSICAL_STORE,1,1752.3,0.0775,1593.00,1616.49675,1593.00,23.49675
2,1572,2020-10-05,B2B,1,1752.3,0.1016,1593.00,1574.26632,1593.00,-18.73368
3,811,2021-08-22,ONLINE,1,1752.3,0.0363,1621.67,1688.69151,1621.67,67.02151
4,606,2022-03-01,B2B,2,1752.3,0.1527,1650.35,2969.44758,3300.70,-331.25242
5,1705,2022-06-24,B2B,2,1752.3,0.1689,1650.35,2912.67306,3300.70,-388.02694
6,248,2022-08-26,ONLINE,3,1752.3,0.0739,1650.35,4868.41509,4951.05,-82.63491
7,1516,2022-12-15,B2B,1,1752.3,0.1762,1650.35,1443.54474,1650.35,-206.80526
8,1425,2023-06-11,ONLINE,2,1752.3,0.0681,1679.02,3265.93674,3358.04,-92.10326
9,184,2023-11-02,B2B,2,1752.3,0.1431,1679.02,3003.09174,3358.04,-354.94826

In [174]:
storage_sales_df["sale_date"] = pd.to_datetime(
    storage_sales_df["sale_date"]
)

storage_sales_df["year"] = (
    storage_sales_df["sale_date"].dt.year
)

storage_yearly = (
    storage_sales_df
    .groupby("year")
    .agg(
        units_sold=("quantity", "sum"),
        average_price=("unit_price", "mean"),
        average_cost=("unit_cost", "mean"),
        average_discount=("discount", "mean"),
        total_revenue=("revenue", "sum"),
        gross_profit=("gross_profit", "sum")
    )
)

storage_yearly["gross_margin"] = (
    storage_yearly["gross_profit"]
    / storage_yearly["total_revenue"]
    * 100
)

storage_yearly.round(2)

,units_sold,average_price,average_cost,average_discount,total_revenue,gross_profit,gross_margin
year,,,,,,,
2020,5,1752.3,1593.00,0.09,8039.73,74.73,0.93
2021,1,1752.3,1621.67,0.04,1688.69,67.02,3.97
2022,8,1752.3,1650.35,0.14,12194.08,-1008.72,-8.27
2023,14,1752.3,1679.02,0.08,22739.07,-767.21,-3.37
2024,13,1752.3,1707.70,0.10,20453.02,-1747.08,-8.54
2025,19,1752.3,1736.37,0.09,30616.71,-2374.32,-7.75
2026,10,1752.3,1765.04,0.11,15857.61,-1792.79,-11.31

In [175]:
storage_yearly["average_revenue_per_unit"] = (
    storage_yearly["total_revenue"]
    / storage_yearly["units_sold"]
)

storage_yearly["average_profit_per_unit"] = (
    storage_yearly["gross_profit"]
    / storage_yearly["units_sold"]
)

storage_yearly[
    [
        "units_sold",
        "average_revenue_per_unit",
        "average_cost",
        "average_profit_per_unit",
        "gross_margin"
    ]
].round(2)

,units_sold,average_revenue_per_unit,average_cost,average_profit_per_unit,gross_margin
year,,,,,
2020,5,1607.95,1593.00,14.95,0.93
2021,1,1688.69,1621.67,67.02,3.97
2022,8,1524.26,1650.35,-126.09,-8.27
2023,14,1624.22,1679.02,-54.80,-3.37
2024,13,1573.31,1707.70,-134.39,-8.54
2025,19,1611.41,1736.37,-124.96,-7.75
2026,10,1585.76,1765.04,-179.28,-11.31

In [176]:
loss_products_df = (
    sales_categories_df
    .groupby("product_name")
    .agg(
        total_revenue=("revenue", "sum"),
        gross_profit=("gross_profit", "sum"),
        units_sold=("quantity", "sum")
    )
    .reset_index()
)

loss_products_df = loss_products_df[
    loss_products_df["gross_profit"] < 0
]

loss_products_df.sort_values(
    "gross_profit"
)

,product_name,total_revenue,gross_profit,units_sold
61,Lenovo Storage Model 15,111588.917220,-7548.362780,70
44,HP Peripherals Model 64,58085.607250,-3303.742750,32
92,Samsung Printing Model 8,45391.484160,-2669.505840,108
30,Dell Monitors Model 43,25172.416500,-2110.333500,31
112,Western Digital Security Model 30,18442.785323,-1267.624677,13
103,TP-Link Servers Model 79,23177.714252,-959.385748,14
98,TP-Link Servers Model 29,6899.974180,-924.745820,6
91,Samsung Printing Model 78,10034.130150,-645.909850,7
21,Acer Computers Model 71,10671.785080,-635.044920,34
4,ASUS Components Model 22,8489.646000,-594.954000,38
12,Acer Computers Model 1,9991.399000,-589.701000,397
42,HP Peripherals Model 44,27702.464140,-510.635860,26
77,Logitech Accessories Model 57,3687.090330,-410.219670,7
11,ASUS Components Model 92,5970.074880,-399.025120,6
105,TP-Link Servers Model 9,43653.049416,-344.470584,77
9,ASUS Components Model 72,6586.242087,-314.317913,15
95,TP-Link Servers Model 109,11257.946292,-246.043708,9
69,Lenovo Storage Model 85,2117.264490,-187.225510,14
71,Logitech Accessories Model 107,8886.082440,-180.667560,10
3,ASUS Components Model 2,10065.246732,-174.783268,292
47,HP Peripherals Model 94,28295.398791,-172.721209,19
51,LG Networking Model 36,1537.931120,-157.248880,16
75,Logitech Accessories Model 37,3697.954360,-143.255640,23
27,Dell Monitors Model 23,12368.739291,-141.880709,37
110,Western Digital Security Model 120,2606.195790,-120.984210,6
84,Samsung Printing Model 108,4302.919236,-62.300764,4
114,Western Digital Security Model 50,499.738470,-43.941530,15
19,Acer Computers Model 51,466.739760,-38.540240,8
13,Acer Computers Model 101,2055.590955,-32.549045,13
106,TP-Link Servers Model 99,533.313660,-32.036340,9
25,Dell Monitors Model 113,147.939000,-17.361000,6
108,Western Digital Security Model 100,1271.036365,-15.223635,12
67,Lenovo Storage Model 65,548.203048,-15.046952,21
37,HP Peripherals Model 114,316.152032,-12.887968,9
57,LG Networking Model 86,2162.071660,-8.728340,9

### Análisis de rentabilidad por producto

Después de analizar la evolución de las ventas y comparar las categorías, profundizamos en la rentabilidad de los productos individuales.

Calcularemos la facturación, los costes, el beneficio bruto y el margen de cada producto. También examinaremos los precios, los descuentos y los costes unitarios para comprender mejor las diferencias de rentabilidad.

A partir de estos resultados, identificaremos los productos cuyo beneficio bruto acumulado es negativo y cuantificaremos su impacto económico.

El objetivo es determinar qué referencias requieren una investigación adicional y disponer de información que permita plantear posibles medidas comerciales.

In [188]:
sales_categories_df["effective_unit_price"] = (
    sales_categories_df["unit_price"] * (1 - sales_categories_df["discount"])
)

sales_categories_df["unit_gross_profit"] = (
    sales_categories_df["effective_unit_price"] - sales_categories_df["unit_cost"]
)

sales_categories_df[
    [
        "product_name",
        "unit_price",
        "discount",
        "effective_unit_price",
        "unit_cost",
        "unit_gross_profit"
    ]
].head(10)

,product_name,unit_price,discount,effective_unit_price,unit_cost,unit_gross_profit
0,Samsung Printing Model 8,458.70,0.0534,434.205420,462.04,-27.834580
1,Dell Monitors Model 3,68.97,0.0518,65.397354,61.10,4.297354
2,ASUS Components Model 12,1310.76,0.2107,1034.582868,1100.24,-65.657132
3,Samsung Printing Model 118,309.38,0.0386,297.437932,245.25,52.187932
4,Samsung Printing Model 28,1419.99,0.2015,1133.862015,1082.37,51.492015
5,Acer Computers Model 11,1043.62,0.0441,997.596358,839.85,157.746358
6,Lenovo Storage Model 65,28.88,0.0351,27.866312,26.80,1.066312
7,Samsung Printing Model 38,272.25,0.0456,259.835400,237.15,22.685400
8,Samsung Printing Model 88,527.50,0.0777,486.513250,439.52,46.993250
9,Dell Monitors Model 23,361.51,0.1520,306.560480,335.54,-28.979520

In [189]:
product_profitability_df = (
    sales_categories_df
    .groupby("product_name")
    .agg(
        total_revenue=("revenue", "sum"),
        total_cost=("total_cost", "sum"),
        gross_profit=("gross_profit", "sum"),
        units_sold=("quantity", "sum"),
        average_discount=("discount", "mean"),
        average_unit_price=("unit_price", "mean"),
        average_unit_cost=("unit_cost", "mean"),
    )
    .reset_index()
)

product_profitability_df["gross_margin"] = (
    product_profitability_df["gross_profit"]
    / product_profitability_df["total_revenue"]
    * 100
)

product_profitability_df = product_profitability_df.sort_values(
    "gross_profit"
).reset_index(drop=True)

product_profitability_df.head(10)

,product_name,total_revenue,total_cost,gross_profit,units_sold,average_discount,average_unit_price,average_unit_cost,gross_margin
0,Lenovo Storage Model 15,111588.917220,119137.28,-7548.362780,70,0.096506,1752.30,1699.262353,-6.764438
1,HP Peripherals Model 64,58085.607250,61389.35,-3303.742750,32,0.090714,2007.50,1928.242857,-5.687713
2,Samsung Printing Model 8,45391.484160,48060.99,-2669.505840,108,0.084402,458.70,445.461250,-5.881072
3,Dell Monitors Model 43,25172.416500,27282.75,-2110.333500,31,0.106771,907.50,879.096429,-8.383516
4,Western Digital Security Model 30,18442.785323,19710.41,-1267.624677,13,0.094986,1590.43,1515.095714,-6.873282
5,TP-Link Servers Model 79,23177.714252,24137.10,-959.385748,14,0.103533,1839.91,1717.251667,-4.139260
6,TP-Link Servers Model 29,6899.974180,7824.72,-924.745820,6,0.111767,1294.70,1304.120000,-13.402163
7,Samsung Printing Model 78,10034.130150,10680.04,-645.909850,7,0.054950,1514.70,1525.720000,-6.437128
8,Acer Computers Model 71,10671.785080,11306.83,-635.044920,34,0.092513,344.30,332.907333,-5.950691
9,ASUS Components Model 22,8489.646000,9084.60,-594.954000,38,0.095771,247.50,238.885714,-7.007995

### Identificar los productos con pérdidas

In [ ]:
loss_making_products_df = product_profitability_df[
    product_profitability_df["gross_profit"] < 0
]

loss_making_products_df.head(10)

### Cuantificar el impacto económico

In [190]:
total_loss_making_products = len(loss_making_products_df)

total_gross_losses = loss_making_products_df["gross_profit"].sum()

revenue_from_loss_making_products = (
    loss_making_products_df["total_revenue"].sum()
)

print(f"Productos analizados: {len(product_profitability_df)}")
print(f"Productos con pérdidas: {total_loss_making_products}")
print(f"Pérdida bruta acumulada: {total_gross_losses:,.2f} €")
print(
    f"Facturación de productos deficitarios: "
    f"{revenue_from_loss_making_products:,.2f} €"
)

Productos analizados: 119
Productos con pérdidas: 35
Pérdida bruta acumulada: -25,031.41 €
Facturación de productos deficitarios: 508,681.24 €

In [191]:
loss_making_details_df = (
    sales_categories_df[
        sales_categories_df["product_name"].isin(
            loss_making_products_df["product_name"]
        )
    ]
    .groupby("product_name")
    .agg(
        total_revenue=("revenue", "sum"),
        total_cost=("total_cost", "sum"),
        gross_profit=("gross_profit", "sum"),
        units_sold=("quantity", "sum"),
        average_discount=("discount", "mean"),
        average_unit_price=("unit_price", "mean"),
        average_unit_cost=("unit_cost", "mean")
    )
    .reset_index()
    .sort_values("gross_profit")
)

loss_making_details_df.head(10)

,product_name,total_revenue,total_cost,gross_profit,units_sold,average_discount,average_unit_price,average_unit_cost
17,Lenovo Storage Model 15,111588.917220,119137.28,-7548.362780,70,0.096506,1752.30,1699.262353
13,HP Peripherals Model 64,58085.607250,61389.35,-3303.742750,32,0.090714,2007.50,1928.242857
25,Samsung Printing Model 8,45391.484160,48060.99,-2669.505840,108,0.084402,458.70,445.461250
10,Dell Monitors Model 43,25172.416500,27282.75,-2110.333500,31,0.106771,907.50,879.096429
33,Western Digital Security Model 30,18442.785323,19710.41,-1267.624677,13,0.094986,1590.43,1515.095714
28,TP-Link Servers Model 79,23177.714252,24137.10,-959.385748,14,0.103533,1839.91,1717.251667
27,TP-Link Servers Model 29,6899.974180,7824.72,-924.745820,6,0.111767,1294.70,1304.120000
24,Samsung Printing Model 78,10034.130150,10680.04,-645.909850,7,0.054950,1514.70,1525.720000
7,Acer Computers Model 71,10671.785080,11306.83,-635.044920,34,0.092513,344.30,332.907333
1,ASUS Components Model 22,8489.646000,9084.60,-594.954000,38,0.095771,247.50,238.885714